version: "3.7"
services:
  static:
    image: chirag14/static
    volumes:
      - data-volume:/usr/home/static/
  code:
    image: chirag14/code
    deploy:
      replicas: 4
    ports:
      - 8084:8080
volumes:
  data-volume:
